name: Mi Primer Workflow
on: push

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Saludar al mundo
              run: echo "Hola, mundo desde github actions!"

            - name: Mostrar informacion del evento
              run: |
                echo "Repositorio: ${{ github.repository }}"
                echo "Branch: $GITHUB_REF"
                echo "Quien hizo el push: $GITHUB_ACTOR"
            
            - name: Mostrar fecha y hora
              run: |
                echo " Fecha actual: $(date)"

            - name: Hacer checkout del c贸digo
              uses: actions/checkout@v3

            - name: Configurar Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20
                cache: 'yarn'

            - name: Verificar Node.js
              run: |
                echo "Node.js version: $(node -v)"
                echo "Yarn version: $(yarn -v)"

            - name: Instalar dependencias
              run: |
                yarn install --frozen-lockfile

            - name: Verificar sintaxis con ESLint
              run: |
                yarn lint

            - name: Construir proyecto React
              run: |
                yarn build

            - name: Mostrar archivos generados
              run: |
                echo "Archivos en el directorio dist:"
                ls -la dist/

            - name: Subir artefactos de construcci贸n
              uses: actions/upload-artifact@v4
              with:
                name: react-build-artifacts
                path: dist/
                retention-days: 30

            - name: Crear archivo de informaci贸n del build
              run: |
                echo "Build Information" > build-info.txt
                echo "==================" >> build-info.txt
                echo "Fecha: $(date)" >> build-info.txt
                echo "Commit: ${{ github.sha }}" >> build-info.txt
                echo "Branch: ${{ github.ref_name }}" >> build-info.txt
                echo "Repositorio: ${{ github.repository }}" >> build-info.txt
                echo "Actor: ${{ github.actor }}" >> build-info.txt
                cat build-info.txt

            - name: Subir informaci贸n del build
              uses: actions/upload-artifact@v3
              with:
                name: build-info
                path: build-info.txt
                retention-days: 30

